services:
  backend:
    build:
      context: ../url_shortener_backend
      dockerfile: Dockerfile
    env_file:
      - ../url_shortener_backend/.env
    ports:
      - "5000:5000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ../url_shortener_backend:/app
      - /app/node_modules
      - /app/.pnpm-store

  frontend:
    build:
      context: ../url_shortener_frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../url_shortener_frontend:/app
      - /app/node_modules
      - /app/.pnpm-store
    depends_on:
      - backend
